$schema: https://json-schema.org/draft/2020-12/schema
$id: https://github.com/chdorner/keytographer/config.schema.json
title: KeytographerConfig
description: A keytographer configuration
type: object
required:
  - canvas
properties:
  name:
    description: The name of the keytographer configuration
    type: string
  keyboard:
    description: The name of the keyboard
    type: string
  canvas:
    type: object
    required:
      - width
      - height
    properties:
      width:
        description: The width of the canvas
        type: integer
      height:
        description: The height of the canvas
        type: integer
      background_color:
        description: "The background color of the canvas in the format of #FFE4E1"
        type: string
        pattern: "^#[a-fA-F0-9]{3}[a-fA-F0-9]{3}?$"
    additionalProperties: false
  layers:
    description: The list of layers in the keymap.
    type: array
    items:
      description: A layer in the keymap.
      type: object
      properties:
        keys:
          description: The list of keys in the layer.
          type: array
          items:
            description: A key in the layer.
            type: object
            properties:
              code:
                description: The code of the keyused when exporting a QMK keymap.
                type: string
              label:
                description: The label of the key.
                anyOf:
                  - type: string
                  - type: number
                  - type: "null"
              shift:
                description: The shift label of the key.
                type: string
              hold:
                description: The hold of the key.
                type: string
              active:
                description: Whether the key is active.
                type: boolean
      required:
        - keys
  layout:
    type: object
    required:
      - keys
    properties:
      keys:
        description: The list of keys in the layout with their coordinates
        type: array
        items:
          description: A key in a layout
          type: object
          properties:
            x:
              description: The x coordinate of the key, measured in key units
              type: number
            y:
              description: The y coordinate of the key, measured in key units
              type: number
            w:
              description: The width of the key, measured in key units, defaults to 1.0
              type: number
            h:
              description: The height of the key, measured in key units, defaults to 1.0
              type: number
    additionalProperties: false
